adds missing gem dependency that prevented bundle exec rake spec from running
from https://travis-ci.org/chef-cookbooks/chef-client/jobs/84023704
$ bundle exec rake spec
rake aborted!
LoadError: cannot load such file -- kitchen
/home/travis/build/chef-cookbooks/chef-client/vendor/bundle/ruby/2.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'

I don't know why test-kitchen is excluded by design, but removing it from the "--without" allows bundle exec rake spec to complete:

Finished in 2 minutes 10.8 seconds (files took 2.09 seconds to load)
41 examples, 0 failures